# Generated by Django 4.2 on 2023-04-16 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_registration.department_details')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Course_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_details_name', to='course_registration.student_details')),
                ('student_roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_details_roll', to='course_registration.student_details')),
            ],
        ),
        migrations.CreateModel(
            name='Department_wise_Course_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=50)),
                ('department_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_registration.department_details')),
            ],
        ),
    ]
