# Generated by Django 4.2 on 2023-04-16 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_course_details',
            name='course_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_details_name', to='course_registration.department_wise_course_details'),
        ),
    ]
