# Generated by Django 4.2 on 2023-04-18 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0003_alter_student_course_details_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class_Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=10)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_registration.student_details')),
            ],
            options={
                'unique_together': {('class_name', 'student_id')},
            },
        ),
    ]
