# Generated by Django 4.2 on 2023-04-18 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0004_class_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_registration.class_details')),
                ('first_hour_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_hour_timetables', to='course_registration.department_wise_course_details')),
                ('second_hour_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_hour_timetables', to='course_registration.department_wise_course_details')),
                ('third_hour_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_hour_timetables', to='course_registration.department_wise_course_details')),
            ],
            options={
                'unique_together': {('class_id',)},
            },
        ),
    ]
