# Generated by Django 4.2 on 2023-04-24 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0006_rename_timetable_time_table_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resumes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(null=True, upload_to='')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_registration.student_details')),
            ],
        ),
    ]
