# Generated by Django 4.2 on 2023-04-25 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0008_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
