# Generated by Django 4.2 on 2023-06-08 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0010_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='dob',
            field=models.CharField(default='29-12-2001', max_length=10),
        ),
        migrations.AddField(
            model_name='student_details',
            name='gender',
            field=models.CharField(default='F', max_length=10),
        ),
    ]
