# Generated by Django 4.2 on 2023-06-09 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_registration', '0013_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessional', models.IntegerField()),
                ('external', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_registration.department_wise_course_details')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_registration.student_details')),
            ],
        ),
    ]
