from django.urls import path,include
from . import views
from django_email_verification import urls as mail_urls
from course_registration.views import *
urlpatterns=[
    path('verify/<token>',views.verify),
    path('verify_password/<token>/<session_key>',views.verify_password),
    path('error_page/',ErrorPage.as_view()),
    path('token_send/',SendToken.as_view()),
    path('success/',SuccessPage.as_view()),
    path('',MainHomePage.as_view()),
    path('register_user/',RegisterUser.as_view()),
    path('register_user/register_user/',RegisterUser.as_view()),
    path('register_staff/',RegisterStaff.as_view()),
    path('register_staff/register_staff/',RegisterStaff.as_view()),
    path('login_user',LoginUser.as_view),
    path('login_user/',LoginUser.as_view()),
     path('login_user/login_user/',LoginUser.as_view()),
    path('logout_user/',LogoutUser.as_view()),
    path('student-list/',views.studentList,name="student-list"),
    path('student-detail/<str:pk>',views.studentDetail,name="student-detail"),
    path('create/',views.Create,name="create"),
    path('create_new/',views.create_object,name="create"),
    path('update/<str:pk>',views.Update,name="update"),
     path('update_object/<str:pk>',views.update_object,name="update"),
    path('delete/<str:pk>',views.Delete,name="delete"),
     path('delete_obj/<int:pk>/', views.delete_object, name='delete_object'),
    path('home/',HomePageApi.as_view(),name="home"),
    path('dept_course/<str:pk>',views.courseDetails),
    path('add_student',AddStudent.as_view(),name="home"),
    path('update_student/<str:pk>',views.UpdateStudent),
    path('update_student/update/<str:pk>',views.Update),
    path('overview/',views.apiOverview),
    path('home_course',CoursesHomePage.as_view(),name="Courses"),
    path('add_course/<str:roll>',AddCourse.as_view(),name="Add Courses"),
    path('add_course/courseCreate/',views.courseCreate,name="courseCreate"),
    path('view_course/<str:roll>',ViewCourses.as_view(),name="View_Courses"),
    path('delete_course/<str:roll>',DeleteCourse.as_view(),name="Delete_Courses"),
    path('delete_course_wise/<str:roll>/<str:course_id>',DeleteSingleCourse.as_view()),
    path('home_class/',ClassHomePage.as_view(),name="View Classes"),
    path('add_class/<str:roll>',AddClassStudent.as_view(),name="Add Classes"),
    path('add_class/Class_StudentCreate/',views.Class_StudentCreate,name="Class_StudentCreate"),
    path('view_class_students/',ViewClassStudents.as_view()),
    path('delete_class/<str:roll>',DeleteClass.as_view()),
    path('timetable/',TimeTable.as_view()),
    path('createTimeTable/',views.createTimeTable),
    path('view_time_table/<str:class_title>',ViewTimeTable.as_view()),
    path('choose_class',ChooseClass.as_view()),
    path('set_class',SetClass.as_view()),
    path('view_all_timetables/',ViewAllTimeTables.as_view()),
    path('add_home_class/',AddClassHomePage.as_view()),
    path('add_class/',AddClass.as_view()),
    path('add_class/create_class/',ClassObjectCreate.as_view()),
    path('delete_section/<str:class_id>/',DeleteSection.as_view()),
    path('search_student/',SearchStudentHome.as_view()),
    path('search_student/searchStudent/',SearchStudentHome.as_view()),
    path('search_student/topNCourse',TopNthCourse.as_view()),
    path('view_pdf/',ViewPDF.as_view()),
    path('resume_upload/',ResumeUpload.as_view()),
    path('resume_upload/save_resume/',SaveResume.as_view()),
    path('view_all_resumes/',ViewAllResumes.as_view()),
    path('view_pdf/media/<str:file_name>',ViewPDFFile.as_view()),
    path('email/',include(mail_urls)),
    path('update_password_home/update_password/',views.update_password),
    path('update_password_home/',views.update_password_home),
    path('dashboard/',views.dashboard_view),
    path('unauthorized/',views.unauthorized),

    path('student_course/',views.student_course),
    path('get_student_course/<str:pk>/',views.studentCourseDetails),
    path('get_course_by_id/<str:pk>',views.courseDetailsById),
    path('delete_course_student_object/<str:pk>',views.delete_course_student_object),


    path('attendance_post/',views.attendance_post),
    path('get_attendance/<str:pk>',views.getStudentAttendance),
    path('get_attendance_by_date/<str:date>',views.getAttendanceByDate),

    path('marks_post/',views.marks_post),
    path('get_marks/<str:stud_id>',views.getMarks),
    path('get_course_by_name/<str:name>',views.getCourseByName),

    path('course_student/',views.studentCourseByName)
   
]                                                                                                                                                                                                                                                                                                                                                           